Jenkinsfile
=> Fix deploy for master build

Jenkinsfile
Enable build-server profile to get content signed.
=> Bug 578192 - The SimRel 2022-03 M1 contribution is unsigned

releng/org.eclipse.linuxtools.target/linuxtools-e4.23.target
To pick up Xerces 2.12.2 for a CVE fix.
=> Build against latest Orbit I-build

libhover/org.eclipse.linuxtools.cdt.libhover.devhelp/src/org/eclipse/linuxtools/internal/cdt/libhover/devhelp/ParseDevHelp.java, rpm/org.eclipse.linuxtools.rpm.ui.editor/src/org/eclipse/linuxtools/internal/rpm/ui/editor/Activator.java, rpm/org.eclipse.linuxtools.rpm.ui.editor/src/org/eclipse/linuxtools/internal/rpm/ui/editor/RpmPackageBuildProposalsJob.java, rpm/org.eclipse.linuxtools.rpm.ui.editor/src/org/eclipse/linuxtools/internal/rpm/ui/editor/SpecfileCompletionProcessor.java
=> Warning fixes

Jenkinsfile
=> Update Jenkinsfile for stable-8.6

containers/org.eclipse.linuxtools.docker.integration.tests/src/org/eclipse/linuxtools/docker/integration/tests/ui/ImageTabTest.java, pom.xml, releng/org.eclipse.linuxtools.target/linuxtools-e4.24.target, releng/org.eclipse.linuxtools.target/pom.xml, rpm/org.eclipse.linuxtools.rpm.core.tests/src/org/eclipse/linuxtools/rpm/core/tests/DownloadPrepareSourcesTest.java, rpm/org.eclipse.linuxtools.rpm.createrepo.tests/src/org/eclipse/linuxtools/internal/rpm/createrepo/tests/CreaterepoProjectCreatorTest.java, rpm/org.eclipse.linuxtools.rpm.createrepo.tests/src/org/eclipse/linuxtools/internal/rpm/createrepo/wizard/tests/CreaterepoWizardTest.java
=> Fix build against 2022-03/4.24-I-builds repos

containers/org.eclipse.linuxtools.docker.ui/src/org/eclipse/linuxtools/internal/docker/ui/wizards/WizardUtils.java
Contributed by STMicroelectronics
Signed-off-by: Torbjörn SVENSSON <torbjorn.svensson@st.com>
=> Prevent NPE if docker connection is not avilable

libhover/org.eclipse.linuxtools.cdt.libhover.devhelp/src/org/eclipse/linuxtools/internal/cdt/libhover/devhelp/DevHelpSAXParser.java, libhover/org.eclipse.linuxtools.cdt.libhover.devhelp/src/org/eclipse/linuxtools/internal/cdt/libhover/devhelp/HTMLSAXParser.java, libhover/org.eclipse.linuxtools.cdt.libhover.devhelp/src/org/eclipse/linuxtools/internal/cdt/libhover/devhelp/HTMLSAXParserOld.java, libhover/org.eclipse.linuxtools.cdt.libhover.devhelp/src/org/eclipse/linuxtools/internal/cdt/libhover/devhelp/ParseDevHelp.java
- fix #41
- add new SAXParser to handle the new gtk-doc devhelp2 format where
references are to a single file and do not include links
- rename HTMLSaxParser to HTMLSAXParserOld and move to new file
- create new file HTMLSAXParser which parses the new format
- support for devhelp2 files only, if no links exist for devhelp
file, bail on parsing
=> ArrayIndexOutOfBoundsException thrown while parsing devhelp2

containers/org.eclipse.linuxtools.docker.ui/src/org/eclipse/linuxtools/internal/docker/ui/jobs/CopyFromDockerJob.java
There were some minor issues with parallel running threads. It is
extremely unlikely that they caused any real issues, but they did
trigger unnecessary log messages.
=> Bug 575057: Followup improvements

valgrind/org.eclipse.linuxtools.valgrind.cachegrind.tests/resources/multiProcTest/parent.cpp, valgrind/org.eclipse.linuxtools.valgrind.massif.tests/resources/multiProcTest/parent.c
- fix execv calls for multiProcTests
=> Fix valgrind test failures

Jenkinsfile, releng/container-build/Dockerfile
Change-Id: I05829bcdbeb0ace18052e1ad00052e8b4baf9cd1
For eclipse-platform/eclipse.platform.releng.aggregator#293
=> Update Dockerfile and build to use Java 17

pom.xml
For the support of upstream JUnit bundle names.
=> Move to Tycho 3.0.0-SNAPSHOT

releng/org.eclipse.linuxtools.target/linuxtools-e4.26.target
What will become CDT 11 for December release
=> Switch to new CDT nightly build

containers/org.eclipse.linuxtools.docker.integration.tests/META-INF/MANIFEST.MF, containers/org.eclipse.linuxtools.docker.ui.tests/src/org/eclipse/linuxtools/internal/docker/ui/testutils/CustomMatchers.java
Signed-off-by: Stephane Bouchet <sbouchet@redhat.com>
Change-Id: I42f286bec8e5173441262b4f7b7e9850c7b77809
=> fix hamcrest resolution with Java17 and eclipse 4.25

releng/org.eclipse.linuxtools.docker-site/category.xml, releng/org.eclipse.linuxtools.target/linuxtools-e4.26.target
It has been part of the JVM since Java 6!
=> Remove javax.xml.stream

releng/container-build/Dockerfile, rpm/org.eclipse.linuxtools.rpm.createrepo.tests/src/org/eclipse/linuxtools/internal/rpm/createrepo/tests/CreaterepoTest.java
=> Various improvements 

changelog/org.eclipse.linuxtools.changelog.core/src/org/eclipse/linuxtools/internal/changelog/core/actions/ChangeLogAction.java, profiling/org.eclipse.linuxtools.profiling.launch/src/org/eclipse/linuxtools/internal/profiling/launch/LocalFileProxy.java, rpm/org.eclipse.linuxtools.rpm.core.tests/src/org/eclipse/linuxtools/rpm/core/tests/DownloadPrepareSourcesTest.java, rpm/org.eclipse.linuxtools.rpm.core.tests/src/org/eclipse/linuxtools/rpm/core/tests/RPMProjectTest.java, rpm/org.eclipse.linuxtools.rpm.core/src/org/eclipse/linuxtools/rpm/core/IRPMConstants.java, rpm/org.eclipse.linuxtools.rpm.createrepo.tests/src/org/eclipse/linuxtools/internal/rpm/createrepo/form/tests/ICreaterepoTestConstants.java, rpm/org.eclipse.linuxtools.rpm.ui.editor/src/org/eclipse/linuxtools/internal/rpm/ui/editor/preferences/PreferenceConstants.java
Simpler than requesting the system property.
=> Use File.separator

changelog/org.eclipse.linuxtools.changelog.ui.tests/META-INF/MANIFEST.MF, containers/org.eclipse.linuxtools.docker.ui.tests/META-INF/MANIFEST.MF, profiling/org.eclipse.linuxtools.profiling.provider.tests/META-INF/MANIFEST.MF, releng/org.eclipse.linuxtools.docker-site/category.xml, releng/org.eclipse.linuxtools.target/linuxtools-e4.28.target, systemtap/org.eclipse.linuxtools.callgraph/src/org/eclipse/linuxtools/internal/callgraph/StapGraph.java, systemtap/org.eclipse.linuxtools.callgraph/src/org/eclipse/linuxtools/internal/callgraph/graphlisteners/StapGraphMouseListener.java
Some code and dependencies adjusted accordingly
=> Update to 2023-06 dependencies

Jenkinsfile, releng/container-build/Dockerfile
Instead of having them in the docker image and depend on Fedora versions which are no longer as uptodate as they have been.
=> Use tools for Java and Maven

containers/org.eclipse.linuxtools.docker.editor.ls/pom.xml
Changelog
https://github.com/rcjsuen/dockerfile-language-server-nodejs/blob/master/CHANGELOG.md#0102---2023-06-01
=> Update to Docker LS 0.10.2

releng/org.eclipse.linuxtools.target/linuxtools-e4.29.target
=> Switch Guava to latest version

containers/org.eclipse.linuxtools.docker.core/META-INF/MANIFEST.MF, releng/org.eclipse.linuxtools.docker-site/category.xml, releng/org.eclipse.linuxtools.target/linuxtools-e4.29.target
Whatever used in Eclipse Platform.
=> Switch javax.annotation to jakarta-annotation

containers/org.eclipse.linuxtools.docker.core/META-INF/p2.inf
Docker core is non functional without it.
=> Make sure jffi.native fragment is installed

releng/org.eclipse.linuxtools.target/linuxtools-e4.29.target
* Bouncycastle to 1.76
* Guava to 32.1.2
=> Update dependencies to new versions

releng/org.eclipse.linuxtools.target/linuxtools-e4.29.target
Fixes the build as the nightly referenced has changed.
=> Switch to Orbit 2023-09 M3

releng/org.eclipse.linuxtools.target/linuxtools-e4.30.target
Jackson to 2.15.3.
Guava to 32.1.3.
=> Update maven dependencies

releng/org.eclipse.linuxtools.target/linuxtools-e4.30.target
Had to split Reddeer to separate location as it's not in simrel anymore.
=> Update to latest deps

changelog/org.eclipse.linuxtools.changelog-feature/feature.xml, changelog/org.eclipse.linuxtools.changelog.c-feature/feature.xml, changelog/org.eclipse.linuxtools.changelog.java-feature/feature.xml, containers/org.eclipse.linuxtools.docker-feature/feature.xml, containers/org.eclipse.linuxtools.docker.editor.ls-feature/feature.xml, containers/org.eclipse.linuxtools.docker.tests-feature/feature.xml, containers/org.eclipse.linuxtools.jdt.docker.launcher-feature/feature.xml, gcov/org.eclipse.linuxtools.gcov-feature/feature.xml, gprof/org.eclipse.linuxtools.gprof-feature/feature.xml, javadocs/org.eclipse.linuxtools.javadocs-feature/feature.xml, libhover/org.eclipse.linuxtools.cdt.libhover-feature/feature.xml, libhover/org.eclipse.linuxtools.cdt.libhover.devhelp-feature/feature.xml, libhover/org.eclipse.linuxtools.cdt.libhover.newlib-feature/feature.xml, man/org.eclipse.linuxtools.man-feature/feature.xml, perf/org.eclipse.linuxtools.perf-feature/feature.xml, profiling/org.eclipse.linuxtools.dataviewers-feature/feature.xml, profiling/org.eclipse.linuxtools.profiling-feature/feature.xml, profiling/org.eclipse.linuxtools.profiling.remote-feature/feature.xml, rpm/org.eclipse.linuxtools.rpm-feature/feature.xml, systemtap/org.eclipse.linuxtools.callgraph-feature/feature.xml, systemtap/org.eclipse.linuxtools.systemtap-feature/feature.xml, vagrant/org.eclipse.linuxtools.vagrant-feature/feature.xml, valgrind/org.eclipse.linuxtools.valgrind-feature/feature.xml
As started in https://github.com/eclipse-pde/eclipse.pde/issues/730 it makes them easier to grasp.
=> Remove irrelevant parts from feature.xml

releng/container-build/Dockerfile
* Fedora 39
* Java 21
* Maven 3.9.6
=> Update docker image

rpm/org.eclipse.linuxtools.rpm.core.tests/src/org/eclipse/linuxtools/rpm/core/tests/DownloadPrepareSourcesTest.java
See https://rpm-software-management.github.io/rpm/manual/dynamic_specs.html for the *-SPECPARTS extra dir details
=> Fix rpm tests with RPM 4.19

profiling/org.eclipse.linuxtools.profiling.launch/src/org/eclipse/linuxtools/profiling/launch/RemoteProxyCMainTab.java, profiling/org.eclipse.linuxtools.tools.launch.core/src/org/eclipse/linuxtools/tools/launch/core/factory/CdtSpawnerProcessFactory.java, valgrind/org.eclipse.linuxtools.valgrind.core/src/org/eclipse/linuxtools/internal/valgrind/core/ValgrindCommand.java
Use the replacement method with Mode.CONSOLE
=> Stop using deprecated PTY.isSupported method

containers/org.eclipse.linuxtools.docker.editor.ls/plugin.xml
Fixes https://github.com/eclipse-linuxtools/org.eclipse.linuxtools/issues/292
=> Support Containerfile

Jenkinsfile
=> Stop using deprecated label in Jenkinsfile

pom.xml
This is for Maven plugins and there are none in this project. Fixes warning in the build.
=> Remove prerequisites

changelog/org.eclipse.linuxtools.changelog-feature/build.properties, changelog/org.eclipse.linuxtools.changelog.c-feature/build.properties, changelog/org.eclipse.linuxtools.changelog.java-feature/build.properties, rpm/org.eclipse.linuxtools.rpm-feature/build.properties, vagrant/org.eclipse.linuxtools.vagrant-feature/build.properties
=> Remove useless src.includes

containers/org.eclipse.linuxtools.docker.editor.ls.tests/META-INF/MANIFEST.MF, containers/org.eclipse.linuxtools.docker.ui.tests/META-INF/MANIFEST.MF, javadocs/org.eclipse.linuxtools.javadocs.tests/META-INF/MANIFEST.MF, libhover/org.eclipse.linuxtools.cdt.libhover.tests/META-INF/MANIFEST.MF
=> Add Bundle-Vendor OSGi metadata in tests

Jenkinsfile, pom.xml
Cleanups and renames the build-server to profile as nothing else happens in it anymore.
=> Sign only master build

containers/org.eclipse.linuxtools.docker.core/src/org/eclipse/linuxtools/internal/docker/core/DockerClientFactory.java
- add synchronized section in DockerClientFactory.getClient() to ensure that property setting/unsetting is consistent
=> Protect property setting with synchronization in DockerClientFactory

releng/org.eclipse.linuxtools.docker-site/category.xml, releng/org.eclipse.linuxtools.target/linuxtools-e4.31.target
- add org.glassfish.jersey.inject.jersey-hk2 as Docker Client dependency
- fixes #335
=> Fix injection-less stderr warnings being issue for Docker Tooling

releng/org.eclipse.linuxtools.docker-site/category.xml, releng/org.eclipse.linuxtools.target/linuxtools-e4.31.target
- add org.glassfish.jersey.inject.jersey-hk2 as Docker Client dependency
- fixes #335
=> Fix injection-less stderr warnings being issue for Docker Tooling (#339)

Jenkinsfile, pom.xml
- fix Jenkinsfile
- fix mirror sites
=> First changes for stable-8.15 branch

pom.xml, releng/org.eclipse.linuxtools.target/linuxtools-e4.33.target
Also explicitly use swtbot-latest repo as per
https://www.eclipse.org/lists/swtbot-dev/msg00890.html it might fix issues seen in master build.
=> Switch to 2024-09 stream

libhover/org.eclipse.linuxtools.cdt.libhover/src/org/eclipse/linuxtools/internal/cdt/libhover/LibHover.java, perf/org.eclipse.linuxtools.perf/src/org/eclipse/linuxtools/internal/perf/ui/PerfDoubleClickAction.java, rpm/org.eclipse.linuxtools.rpm.ui.editor.tests/src/org/eclipse/linuxtools/rpm/ui/editor/tests/HeaderRecognitionTest.java, rpm/org.eclipse.linuxtools.rpm.ui.editor.tests/src/org/eclipse/linuxtools/rpm/ui/editor/tests/parser/SpecfileDefineTest.java, systemtap/org.eclipse.linuxtools.systemtap.graphing.ui/src/org/eclipse/linuxtools/systemtap/graphing/ui/datadisplay/DataGrid.java
The rest of the change is save actions modernizing code.
=> Remove unnecessary casts

containers/org.eclipse.linuxtools.docker.core/src/org/eclipse/linuxtools/internal/docker/core/HttpHijackWorkaround.java, releng/org.eclipse.linuxtools.target/linuxtools-e4.33.target
- fix HttpHijackWorkaround due to changed dependencies
=> Update Linux Tools to use docker-client 8.0.2

Jenkinsfile, pom.xml
- set up mirror sites
- modify Jenkinsfile
=> First changes for stable-8.16 branch

pom.xml
=> Stop jarsigning

pom.xml, releng/org.eclipse.linuxtools.target/linuxtools-latest.target
As the build breaks for each release let's have a latest one so this doesn't have to be changed every 3 months.
=> Have single latest target

containers/org.eclipse.linuxtools.docker.core/src/org/eclipse/linuxtools/internal/docker/core/DockerContainerConfig.java, containers/org.eclipse.linuxtools.docker.core/src/org/eclipse/linuxtools/internal/docker/core/DockerImageInfo.java, containers/org.eclipse.linuxtools.docker.ui.tests/src/org/eclipse/linuxtools/internal/docker/ui/testutils/MockImageInfoFactory.java, releng/org.eclipse.linuxtools.target/linuxtools-latest.target
- fix some changes that have been made to configuration structures
=> Update Linux Tools to use docker-client 8.0.3

Jenkinsfile
=> Don't specify jnlp image

profiling/org.eclipse.linuxtools.dataviewers.charts/src/org/eclipse/linuxtools/internal/dataviewers/charts/view/ChartFactory.java, profiling/org.eclipse.linuxtools.dataviewers.piechart/META-INF/MANIFEST.MF, profiling/org.eclipse.linuxtools.dataviewers.piechart/src/org/eclipse/linuxtools/internal/dataviewers/piechart/PieChart.java, profiling/org.eclipse.linuxtools.dataviewers.piechart/src/org/eclipse/linuxtools/internal/dataviewers/piechart/PieChartPaintListener.java, releng/org.eclipse.linuxtools.target/linuxtools-latest.target, systemtap/org.eclipse.linuxtools.systemtap.graphing.ui/META-INF/MANIFEST.MF, systemtap/org.eclipse.linuxtools.systemtap.graphing.ui/src/org/eclipse/linuxtools/internal/systemtap/graphing/ui/charts/AbstractChartWithAxisBuilder.java, systemtap/org.eclipse.linuxtools.systemtap.graphing.ui/src/org/eclipse/linuxtools/internal/systemtap/graphing/ui/charts/AreaChartBuilder.java, systemtap/org.eclipse.linuxtools.systemtap.graphing.ui/src/org/eclipse/linuxtools/internal/systemtap/graphing/ui/charts/BarChart.java, systemtap/org.eclipse.linuxtools.systemtap.graphing.ui/src/org/eclipse/linuxtools/internal/systemtap/graphing/ui/charts/BarChartBuilder.java, systemtap/org.eclipse.linuxtools.systemtap.graphing.ui/src/org/eclipse/linuxtools/internal/systemtap/graphing/ui/charts/LineChartBuilder.java, systemtap/org.eclipse.linuxtools.systemtap.graphing.ui/src/org/eclipse/linuxtools/internal/systemtap/graphing/ui/charts/ScatterChartBuilder.java, systemtap/org.eclipse.linuxtools.systemtap.graphing.ui/src/org/eclipse/linuxtools/internal/systemtap/graphing/ui/charts/listeners/BarChartMouseMoveListener.java, systemtap/org.eclipse.linuxtools.systemtap.graphing.ui/src/org/eclipse/linuxtools/internal/systemtap/graphing/ui/charts/listeners/ChartWithAxisMouseMoveListener.java, systemtap/org.eclipse.linuxtools.systemtap.graphing.ui/src/org/eclipse/linuxtools/internal/systemtap/graphing/ui/charts/listeners/PieChartMouseMoveListener.java, systemtap/org.eclipse.linuxtools.systemtap.graphing.ui/src/org/eclipse/linuxtools/systemtap/graphing/ui/widgets/GraphDiscreteXControl.java, systemtap/org.eclipse.linuxtools.systemtap.ui.ide.tests/src/org/eclipse/linuxtools/systemtap/ui/ide/test/swtbot/TestCreateSystemtapScript.java, valgrind/org.eclipse.linuxtools.valgrind.massif.tests/src/org/eclipse/linuxtools/internal/valgrind/massif/tests/ChartTests.java, valgrind/org.eclipse.linuxtools.valgrind.massif/META-INF/MANIFEST.MF, valgrind/org.eclipse.linuxtools.valgrind.massif/src/org/eclipse/linuxtools/internal/valgrind/massif/charting/ChartEditor.java
Fix some generification warnings while at it.
=> Move to SWTChart 1.0

releng/org.eclipse.linuxtools.target/linuxtools-latest.target
Update guava and remove duplicated osgi-resource-locator.
=> Update target platform

changelog/org.eclipse.linuxtools.changelog-feature/pom.xml, changelog/org.eclipse.linuxtools.changelog.c-feature/pom.xml, changelog/org.eclipse.linuxtools.changelog.java-feature/pom.xml, containers/org.eclipse.linuxtools.docker-feature/pom.xml, containers/org.eclipse.linuxtools.docker.editor.ls-feature/pom.xml, containers/org.eclipse.linuxtools.jdt.docker.launcher-feature/pom.xml, gcov/org.eclipse.linuxtools.gcov-feature/pom.xml, gprof/org.eclipse.linuxtools.gprof-feature/pom.xml, javadocs/org.eclipse.linuxtools.javadocs-feature/pom.xml, libhover/org.eclipse.linuxtools.cdt.libhover-feature/pom.xml, libhover/org.eclipse.linuxtools.cdt.libhover.devhelp-feature/pom.xml, libhover/org.eclipse.linuxtools.cdt.libhover.newlib-feature/pom.xml, man/org.eclipse.linuxtools.man-feature/pom.xml, perf/org.eclipse.linuxtools.perf-feature/pom.xml, perf/org.eclipse.linuxtools.perf.remote-feature/pom.xml, pom.xml, profiling/org.eclipse.linuxtools.dataviewers-feature/pom.xml, profiling/org.eclipse.linuxtools.profiling-feature/pom.xml, profiling/org.eclipse.linuxtools.profiling.remote-feature/pom.xml, releng/org.eclipse.linuxtools.docker-site/category.xml, releng/org.eclipse.linuxtools.docker-site/pom.xml, releng/org.eclipse.linuxtools.releng-site/category.xml, releng/org.eclipse.linuxtools.releng-site/pom.xml, rpm/org.eclipse.linuxtools.rpm-feature/pom.xml, systemtap/org.eclipse.linuxtools.callgraph-feature/pom.xml, systemtap/org.eclipse.linuxtools.systemtap-feature/pom.xml, vagrant/org.eclipse.linuxtools.vagrant-feature/pom.xml, valgrind/org.eclipse.linuxtools.valgrind-feature/pom.xml, valgrind/org.eclipse.linuxtools.valgrind.remote-feature/pom.xml
Let Tycho auto include all sources in the p2 repo and PDE fetch sources when needed.
Prep step for the future when
https://github.com/eclipse-tycho/tycho/pull/5138 land.
=> Stop dealing with source features
