- containers/org.eclipse.linuxtools.docker-feature/p2.inf
- add removeJvmArg statements in Docker Tooling feature p2.inf so new
addJvmArg touchpoint statements are not duplicated when updating
> Bug 578660 - Docker terminal gets InaccessibleObjectException

- containers/org.eclipse.linuxtools.docker.editor.ls/pom.xml
Licensecheck doesn't complain.
Changelog:
https://github.com/rcjsuen/dockerfile-language-server-nodejs/blob/master/CHANGELOG.md#080---2022-01-22
> Update Docker LS to 0.8.0

- libhover/org.eclipse.linuxtools.cdt.libhover.devhelp/src/org/eclipse/linuxtools/internal/cdt/libhover/devhelp/ParseDevHelp.java
- newer format devhelp2 files do not follow the format supported by
ParseDevHelp
- if no anchors for methods/functions, then bail immediately
> ArrayIndexOutOfBoundsException thrown while parsing devhelp2 files

- containers/org.eclipse.linuxtools.docker.editor.ls/META-INF/MANIFEST.MF
- containers/org.eclipse.linuxtools.docker.editor.ls/plugin.xml
- containers/org.eclipse.linuxtools.docker.editor.ls/pom.xml
- add file-patterns specifier for dockerfile ls editor content types
- bump docker ls editor version
> Bug 563169 - [syntax highlighting] Fails for Dockerfile.something

- containers/org.eclipse.linuxtools.docker.editor.ls/pom.xml
Adds suppot for `ADD --link ...` as per
https://github.com/rcjsuen/dockerfile-language-server-nodejs/blob/master/CHANGELOG.md#090---2022-05-04
Licensecheck tool is happy after
https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/2564 and
https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/2565
approved for this release.
> Update to Docker LS 0.9.0

- releng/org.eclipse.linuxtools.target/linuxtools-e4.24.target
- point Orbit to 4.24 RC1 repo (S20220517184036)
- add CVS Orbit repo (R20201118194144) to handle missing items from latest Orbit
> Update linuxtools-e4.24.target file

- containers/org.eclipse.linuxtools.docker.editor.ls.tests/.classpath
- containers/org.eclipse.linuxtools.docker.editor.ls.tests/.settings/org.eclipse.jdt.core.prefs
- containers/org.eclipse.linuxtools.docker.editor.ls.tests/META-INF/MANIFEST.MF
- containers/org.eclipse.linuxtools.docker.editor.ls.tests/src/org/eclipse/linuxtools/docker/editor/ls/tests/TestLanguageServers.java
- containers/org.eclipse.linuxtools.docker.editor.ls/.classpath
- containers/org.eclipse.linuxtools.docker.editor.ls/.settings/org.eclipse.jdt.core.prefs
- containers/org.eclipse.linuxtools.docker.editor.ls/META-INF/MANIFEST.MF
- containers/org.eclipse.linuxtools.docker.editor.ls/src/org/eclipse/linuxtools/docker/editor/ls/DockerfileLanguageServer.java
- containers/org.eclipse.linuxtools.docker.editor.ls/src/org/eclipse/linuxtools/docker/editor/ls/InitializeLaunchConfigurations.java
It relies on WWD and TM4E and both have moved to Java 17 for September
release.
> Move Docker editor plugin to Java 17

- gcov/org.eclipse.linuxtools.gcov.core/src/org/eclipse/linuxtools/internal/gcov/parser/GcdaRecordsParser.java
- gcov/org.eclipse.linuxtools.gcov.core/src/org/eclipse/linuxtools/internal/gcov/parser/GcnoRecordsParser.java
- gcov/org.eclipse.linuxtools.gcov.core/src/org/eclipse/linuxtools/internal/gcov/utils/GcovStringReader.java
- gcc 12 support has added a new chksum field in header
- gcc 12 support has changed length field to be in bytes instead
of words
- fixes #71
> Modify Linux Tools gcov support to handle gcc 12

- releng/org.eclipse.linuxtools.target/linuxtools-e4.25.target
By switching more libraries to be used from platform p2 repo and
adjusting symbolic names to match the maven central ones.
> Fix build with 4.25 stream

- containers/org.eclipse.linuxtools.docker.core/src/org/eclipse/linuxtools/docker/core/DockerOperationCancelledException.java
- containers/org.eclipse.linuxtools.docker.core/src/org/eclipse/linuxtools/docker/core/IDockerConnection.java
- containers/org.eclipse.linuxtools.docker.core/src/org/eclipse/linuxtools/docker/core/IDockerConnection4.java
- containers/org.eclipse.linuxtools.docker.core/src/org/eclipse/linuxtools/docker/core/IDockerProgressHandler.java
- containers/org.eclipse.linuxtools.docker.core/src/org/eclipse/linuxtools/internal/docker/core/DefaultImagePullProgressHandler.java
- containers/org.eclipse.linuxtools.docker.core/src/org/eclipse/linuxtools/internal/docker/core/DockerConnection.java
- containers/org.eclipse.linuxtools.docker.core/src/org/eclipse/linuxtools/internal/docker/core/DockerMessages.properties
- containers/org.eclipse.linuxtools.docker.ui/src/org/eclipse/linuxtools/internal/docker/ui/commands/PullImageCommandHandler.java
- containers/org.eclipse.linuxtools.docker.ui/src/org/eclipse/linuxtools/internal/docker/ui/wizards/ImageRunSelectionPage.java
This fixes the cancellation of an image pull. I'm afraid I ended up in the API-Hell. Do I need to put `getDefaultPullImageProgressHandler()` into `IDockerConnection4`? It also seems like I have problem with my externalized string. Can I move that to internal?
@jjohnstn
> Docker Pull: Handle cancellation

- containers/org.eclipse.linuxtools.docker.core/src/org/eclipse/linuxtools/internal/docker/core/HttpHijackWorkaround.java
- reverse String.equals() call whereby the getCanonicalName() of a
class may return null
> Fix NPE in HttpHijackWorkaround

- gcov/org.eclipse.linuxtools.gcov.core/META-INF/MANIFEST.MF
- gcov/org.eclipse.linuxtools.gcov.core/pom.xml
- gcov/org.eclipse.linuxtools.gcov.core/src/org/eclipse/linuxtools/internal/gcov/parser/GcdaRecordsParser.java
- modify GcdaRecordsParser.parseGcdaRecord() to handle the gcc12 case where the length of a GCOV_COUNTER_ARCS is actually negative in which case ignore and continue
- fix the logic for an unknown fn for GCOV_COUNTER_ARCS and again ignore and continue
- ignore function tags with zero length
> Bug 580753 - gcov fails with c++ and gcc-12.2.1

- containers/org.eclipse.linuxtools.docker.ui/src/org/eclipse/linuxtools/internal/docker/ui/launch/RunImagePortsTab.java
The old ViewerProperties.checkedElements is removed in platform, hence the new Databinding API is used.
> Adjust RunImagePortsTab to use ViewersObservables API

- profiling/org.eclipse.linuxtools.profiling.tests/src/org/eclipse/linuxtools/profiling/tests/AbstractTest.java
- creation of project is starting an index but we ask for a reindex immediately
- this causes a deadlock to occur
- add a joinIndexer call in AbstractTest preceding the reindex request
> Fix deadlock in Linux Tools tests

- releng/org.eclipse.linuxtools.docker-site/category.xml
- releng/org.eclipse.linuxtools.target/linuxtools-e4.26.target
Moving to upstream symbolic names forces us to do so too.
> Fix build after bouncycastle and slf4j updates in platform

- libhover/org.eclipse.linuxtools.cdt.libhover.devhelp/src/org/eclipse/linuxtools/internal/cdt/libhover/devhelp/ParseDevHelp.java
The devhelp2 format has been introduced in 2005, and the old devhelp 1 format was deprecated in 2017.
The last known project to still publish devhelp 1 format indexes, libxml2 was stopped doing so in January 2022:
https://gitlab.gnome.org/GNOME/libxml2/-/commit/00e618eb0a8a924ee4ba06e3647673310dc856b5
The Devhelp project itself dropped support for devhelp 1 format indexes in July 2021:
https://gitlab.gnome.org/GNOME/devhelp/-/commit/2c3c216dbf4c16dcfb5def8ef24cb380bfceb34b
> Remove support for old devhelp 1 format

- containers/org.eclipse.linuxtools.docker.core/src/org/eclipse/linuxtools/docker/core/DockerCertificateException.java
- containers/org.eclipse.linuxtools.docker.core/src/org/eclipse/linuxtools/docker/core/IDockerConnection.java
- containers/org.eclipse.linuxtools.docker.core/src/org/eclipse/linuxtools/docker/core/IDockerConnection5.java
- containers/org.eclipse.linuxtools.docker.core/src/org/eclipse/linuxtools/internal/docker/core/DockerConnection.java
- containers/org.eclipse.linuxtools.docker.ui/src/org/eclipse/linuxtools/internal/docker/ui/commands/PullImageCommandHandler.java
- Add a new DockerCertificateException class to docker core
- Add a new interface IDockerConnection5 that adds two new methods named pullImageWithHandler() which will replace the current pullImage() methods found in IDockerConnection
- For one of the new pullImageWithHandler() methods, replace the old throws clause which refers to an org.mandas.docker.client exception and refer to the new DockerCertificateException
- label the old pullImage() methods as deprecated and change internal code to use the new methods
- fixes #130
> Add new pullImageWithHandler() methods to DockerConnection

- releng/org.eclipse.linuxtools.docker-site/category.xml
- releng/org.eclipse.linuxtools.target/linuxtools-e4.27.target
- change linuxtools-e4.27 target to use new Orbit repo
- add new jnr stack including a64asm support
- add new a64asm to docker category.xml
> Switch to use new jnr stack

- pom.xml
- releng/org.eclipse.linuxtools.target/linuxtools-e4.28.target
Switch the target platform accordingly.
Fixes https://github.com/eclipse-linuxtools/org.eclipse.linuxtools/issues/167
> Build against 2023-06/4.28 stream

- pom.xml
- releng/org.eclipse.linuxtools.docker-site/pom.xml
- releng/org.eclipse.linuxtools.releng-site/pom.xml
These parameters are no longer needed.
> Cleanup leftovers from old Tycho versions

- gcov/org.eclipse.linuxtools.gcov.core/src/org/eclipse/linuxtools/internal/gcov/parser/Block.java
- gcov/org.eclipse.linuxtools.gcov.core/src/org/eclipse/linuxtools/internal/gcov/parser/GcdaRecordsParser.java
- gcov/org.eclipse.linuxtools.gcov.core/src/org/eclipse/linuxtools/internal/gcov/parser/GcnoFunction.java
- gcov/org.eclipse.linuxtools.gcov.core/src/org/eclipse/linuxtools/internal/gcov/parser/GcnoRecordsParser.java
Fix the problem of Gcov tool inaccurately parsing data file generated by gcc 10.1 and later versions. This problem could cause Gcov tool to not count the return statement at the end of each function.
The basis for fixing this problem is that in the gcov.cc source code of gcc 10.1 and subsequent versions, the index value of entryblock is specified as 0 and that of exitblock is specified as 1. However, in the source code of this project Gcnofuntion.java, the index value of exitblock is set to fnctnBlcks.size()-1 at lines 119 and 120.
Other minor fixes include reducing unnecessary loops in GcnoRecordParser.java and adding sorting operations for arc successor nodes which originally performed in gcc source code and disappear in our tool.
> Fix the problem of Gcov tool inaccurately parsing gcc data file.

- releng/org.eclipse.linuxtools.docker-site/category.xml
Fixes broken installation due to missing dependency
> Add jackson-module-jaxb-annotations to docker site

- containers/org.eclipse.linuxtools.docker.core/META-INF/MANIFEST.MF
To ensure it is installed at runtime as only test packages were requiring it. Making install from update site non usable.
> Explicitly import org.glassfish.jersey.apache.connector package

- containers/org.eclipse.linuxtools.docker.core/src/org/eclipse/linuxtools/internal/docker/core/HttpHijackWorkaround.java
- remove ReaderInterceptorExecutor$UnCloseableStream entry in declared list and its associated field name
- fixes #235
> Fix HttpHijackWorkaround to work with new dependencies/docker-client

- containers/org.eclipse.linuxtools.docker.core/src/org/eclipse/linuxtools/internal/docker/core/CloseableContainer.java
- containers/org.eclipse.linuxtools.docker.ui/src/org/eclipse/linuxtools/docker/ui/launch/ContainerLauncher.java
- add new runCommand to ContainerLauncher that adds seccomp parameter
- specify seccomp unconfined for CloseableContainer used for copying
- fixes #239
> Add seccomp specification support for running and copying files

- containers/org.eclipse.linuxtools.docker.ui/META-INF/MANIFEST.MF
- releng/org.eclipse.linuxtools.docker-site/category.xml
- releng/org.eclipse.linuxtools.target/linuxtools-e4.29.target
Orbit signs the native libs to get MacOS notarization succeed. See https://github.com/eclipse-orbit/orbit-simrel/issues/7 for details.
> Use jffi native from Orbit

- releng/org.eclipse.linuxtools.target/linuxtools-e4.30.target
It's no longer in Platform p2 repo and seems to not be used here too.
> Remove commons-codec from target platform

- pom.xml
- releng/org.eclipse.linuxtools.target/linuxtools-e4.31.target
- releng/org.eclipse.linuxtools.target/pom.xml
This actually fixes the build as 4.30-I-builds are gone now
> Build against 4.31/2024-03 stream

- valgrind/org.eclipse.linuxtools.valgrind.ui.tests/.settings/org.eclipse.jdt.core.prefs
- valgrind/org.eclipse.linuxtools.valgrind.ui.tests/.settings/org.eclipse.jdt.ui.prefs
- valgrind/org.eclipse.linuxtools.valgrind.ui.tests/src/org/eclipse/linuxtools/internal/valgrind/ui/quickfixes/tests/WrongDeallocationResolutionTest.java
First step towards fixing the tests with valgrind 3.22.0 as shipped in fedora 39.
> Format and modernization of o.e.linuxtools.valgrind.ui.tests

- rpm/org.eclipse.linuxtools.rpm.ui.editor/src/org/eclipse/linuxtools/internal/rpm/ui/editor/hyperlink/URLHyperlinkWithMacroDetector.java
Java 20+ no longer accepts %{} (aka rpm macro) in URLs and throw MalformedURLException.
Changed implementation to do macro replacement before creating URL which effectively means no longer inheriting URLHyperlinkDetector.
See https://www.oracle.com/java/technologies/javase/20-relnote-issues.html#JDK-8293590 for details.
> Fix RPM URLHyperlinkWithMacroDetector on Java 20+

- valgrind/org.eclipse.linuxtools.valgrind.tests/src/org/eclipse/linuxtools/internal/valgrind/tests/AbstractValgrindTest.java
Use the new FileLocator.getBundleFileLocation()
> Stop using the deprecated FileLocator.getBundleFile

- valgrind/org.eclipse.linuxtools.valgrind.ui.tests/resources/wrongDeallocTest/wrongDealloc.cpp
- valgrind/org.eclipse.linuxtools.valgrind.ui.tests/src/org/eclipse/linuxtools/internal/valgrind/ui/quickfixes/tests/WrongDeallocationResolutionTest.java
Adjust to changes in valgrind output and thus markers generated by the plugin.
> Fix WrongDeallocationResolutionTest with latest valgrind

- pom.xml
Not used for years, plain broken (Java 11 is not fine for the project) and no intention to bring them back but jacoco still runs and slows down the build and pollutes the build log.
> Get rid of jacoco+sonar configs

- profiling/org.eclipse.linuxtools.profiling.tests/src/org/eclipse/linuxtools/internal/profiling/tests/CProjectHelper.java
It's deprecated for removal and used only in tests.
> Remove call to System.runFinalization()

- changelog/org.eclipse.linuxtools.changelog.ui.tests/src/org/eclipse/linuxtools/changelog/ui/tests/swtbot/AbstractSWTBotTest.java
- perf/org.eclipse.linuxtools.perf.swtbot.tests/src/org/eclipse/linuxtools/internal/perf/swtbot/tests/AbstractSWTBotTest.java
- profiling/org.eclipse.linuxtools.profiling.provider.tests/src/org/eclipse/linuxtools/profiling/provider/tests/PreferencesTest.java
- systemtap/org.eclipse.linuxtools.systemtap.ui.ide.tests/src/org/eclipse/linuxtools/systemtap/ui/ide/test/swtbot/TestCreateSystemtapScript.java
It's not in the target platform for years now so this patch simply reduces noise while trying to stabilize tests.
> Stop dealing with subclipse stats dialog

- containers/org.eclipse.linuxtools.docker.core/src/org/eclipse/linuxtools/internal/docker/core/ProcessLauncher.java
- containers/org.eclipse.linuxtools.docker.editor.ls/src/org/eclipse/linuxtools/docker/editor/ls/InitializeLaunchConfigurations.java
- gcov/org.eclipse.linuxtools.gcov.core/src/org/eclipse/linuxtools/internal/gcov/parser/CovManager.java
- gprof/org.eclipse.linuxtools.gprof.test/src/org/eclipse/linuxtools/internal/gprof/test/GprofTest.java
- gprof/org.eclipse.linuxtools.gprof/src/org/eclipse/linuxtools/internal/gprof/utils/Aggregator.java
- man/org.eclipse.linuxtools.man.core/src/org/eclipse/linuxtools/internal/man/parser/ManParser.java
- perf/org.eclipse.linuxtools.perf/src/org/eclipse/linuxtools/internal/perf/AbstractDataManipulator.java
- perf/org.eclipse.linuxtools.perf/src/org/eclipse/linuxtools/internal/perf/PerfCore.java
- perf/org.eclipse.linuxtools.perf/src/org/eclipse/linuxtools/internal/perf/launch/PerfLaunchConfigDelegate.java
- profiling/org.eclipse.linuxtools.binutils/src/org/eclipse/linuxtools/binutils/utils/STNM.java
- profiling/org.eclipse.linuxtools.ssh.proxy/src/org/eclipse/linuxtools/internal/ssh/proxy/SSHProxyManager.java
- profiling/org.eclipse.linuxtools.tools.launch.core/src/org/eclipse/linuxtools/tools/launch/core/factory/RuntimeProcessFactory.java
- systemtap/org.eclipse.linuxtools.callgraph.core/src/org/eclipse/linuxtools/internal/callgraph/core/SystemTapView.java
- systemtap/org.eclipse.linuxtools.systemtap.ui.ide/src/org/eclipse/linuxtools/internal/systemtap/ui/ide/preferences/PreferenceInitializer.java
- vagrant/org.eclipse.linuxtools.vagrant.core/src/org/eclipse/linuxtools/internal/vagrant/core/VagrantConnection.java
- valgrind/org.eclipse.linuxtools.valgrind.launch/src/org/eclipse/linuxtools/internal/valgrind/launch/ValgrindRemoteProxyLaunchDelegate.java
Use the input/errorReader methods to avoid manual wrapping of the streams.
> Simplify Process streams handling

- containers/org.eclipse.linuxtools.docker.core/META-INF/MANIFEST.MF
- containers/org.eclipse.linuxtools.docker.core/src/org/eclipse/linuxtools/internal/docker/core/DockerClientFactory.java
- containers/org.eclipse.linuxtools.docker.ui.tests/META-INF/MANIFEST.MF
- releng/org.eclipse.linuxtools.docker-site/category.xml
- releng/org.eclipse.linuxtools.target/linuxtools-latest.target
This implies switch from apache httpclient 4.x to 5.x
> Move to docker-client 9.0

- containers/org.eclipse.linuxtools.docker.ui/src/org/eclipse/linuxtools/internal/docker/ui/launch/RunImageMainTab.java
- containers/org.eclipse.linuxtools.docker.ui/src/org/eclipse/linuxtools/internal/docker/ui/launch/RunImageNetworkTab.java
- containers/org.eclipse.linuxtools.docker.ui/src/org/eclipse/linuxtools/internal/docker/ui/launch/RunImageResourcesTab.java
- containers/org.eclipse.linuxtools.docker.ui/src/org/eclipse/linuxtools/internal/docker/ui/launch/RunImageVolumesTab.java
- containers/org.eclipse.linuxtools.docker.ui/src/org/eclipse/linuxtools/internal/docker/ui/wizards/ContainerDataVolumeDialog.java
- containers/org.eclipse.linuxtools.docker.ui/src/org/eclipse/linuxtools/internal/docker/ui/wizards/ContainerEnvironmentVariableDialog.java
- containers/org.eclipse.linuxtools.docker.ui/src/org/eclipse/linuxtools/internal/docker/ui/wizards/ContainerLabelVariableDialog.java
- containers/org.eclipse.linuxtools.docker.ui/src/org/eclipse/linuxtools/internal/docker/ui/wizards/ContainerLinkDialog.java
- containers/org.eclipse.linuxtools.docker.ui/src/org/eclipse/linuxtools/internal/docker/ui/wizards/ContainerPortDialog.java
- containers/org.eclipse.linuxtools.docker.ui/src/org/eclipse/linuxtools/internal/docker/ui/wizards/DockerComposeUpDialog.java
- containers/org.eclipse.linuxtools.docker.ui/src/org/eclipse/linuxtools/internal/docker/ui/wizards/ImageRunNetworkPage.java
- containers/org.eclipse.linuxtools.docker.ui/src/org/eclipse/linuxtools/internal/docker/ui/wizards/ImageRunResourceVolumesVariablesPage.java
- containers/org.eclipse.linuxtools.docker.ui/src/org/eclipse/linuxtools/internal/docker/ui/wizards/ImageRunSelectionPage.java
Make some methods returning non-generic listeners to be method references.
Put some <> to let compiler figure it on its own in other places.
> Fix generics warnings

- containers/org.eclipse.linuxtools.docker.core/META-INF/MANIFEST.MF
- containers/org.eclipse.linuxtools.docker.ui.tests/META-INF/MANIFEST.MF
- releng/org.eclipse.linuxtools.docker-site/category.xml
- releng/org.eclipse.linuxtools.target/linuxtools-latest.target
- fixes unix socket connection errors and switches back to use HTTP 4
> Update Docker Tooling to use docker-client 9.0.3

- .mvn/extensions.xml
Needed as target platform doesn't have a pom and thus updateTarget doesn't work.
> Enable tycho-extension
